# Version and Label are *required*.
version = "vg-1.0"
label = "Example Application"

# The following params are optional, and will be hidden in the launcher if not provided.
webpage = "https://your.application.website"
forums = "https://your.application.website/forums"
discord = "https://your.discord.community/invite"
rss = "https://your.application.website/patchnotes.rss"
posted_image = "https://your.application.website/banner_image.png"

# A valid profile *must* contain a name and exec.
[[profile]]
name = "Awesome App" # Display name of the app.
exec = "app.exe" # Local file path to the application binary.
# Params below are optional.
order = 0 # Numeric sort order.
params = "--be-awesome" # Launch params.
icon = "https://your.application.website/app-icon.png" # Icon to display. May also be a local file path.
architecture = "x64" # Applications with non-native architecture are hidden by default, if arch is specified

[[profile]]
name = "Awesome App (Dev Mode)"
exec = "app.exe"
order = "1"
params = "--debug --verbose"

# A valid file *must* have a path and at least one url.
[[file]]
path = "bin/app.exe" # Local file path to the file
url = [ # List of download mirrors in order of preference.
    "https://your.application.website/app.exe",
    "https://another.mirror/app.exe",
    "http://an.insecure.mirror/app.exe" # Will be ignored if secure patching is enabled (default).
]
# At least one of the following must be provided to support secure patching.
# A file table with hashes can be automatically generated by Manifesto.
# Vanguard uses sha1 by default, but will use the most secure option provided.
md5 = "587bb16b7ae57a697c5381b20253e80a"
sha1 = "6af7bb1928af5bff4f953a6fcf85a9ca61f9af3a"
sha256 = "6a62362c11e91c9f8205c47bbb30833a257c979f663b9a73d3c814ce228fe3dd"
# File size may optionally be specified to improve memory allocation for downloading.
size = 256 # File size in bytes.

[[file]]
path = "lib/awesome.dll"
url = [
    "https://your.application.website/awesome.dll",
    "https://another.mirror/app.dll"
]
sha1 = "6358b5cb2992b884678743e7ab0fdbb6e718a96f"